### ISSUE TITLE
MEASURE_OVERRIDES not implemented in latest versions

### ISSUE THREAD

**Issue by simma101** [coddingtonbear/django-measurement#10]
The MEASURE_OVERRIDES setting does not appear to be implemented in the latest versions meaning custom measurements are broken. 

Patch in my fork uses earlier version code to get it going again, not really tested yet.

**Comment by codingjoe** [comment]
@simma101 you're right about that. We change the design a lot in the last major release, because it's complexity was unmaintainable. I'm sorry for you, but I don't see this feature returning.
