### ISSUE TITLE
Using measurement and unit as inline input group in form?

### ISSUE THREAD

**Issue by DaEMoN33** [coddingtonbear/django-measurement#102]
Hello,

I'm trying to achieve an inline input group in a form in Django. I've tried for days to get the unit_choices to show up in a way that would work for this, but I'm still struggling, so I'm wondering if this is even possible.

As you can see I have a MeasureBase class "Height" that takes three units.

I have attached a mockup of what I envision...

Thanks for django-measurement and thanks in advance for any advice you may have!

![input_group](https://user-images.githubusercontent.com/8888782/92024368-1e3ed680-ed2c-11ea-9a65-0c7bc538a68f.png)
![input_group2](https://user-images.githubusercontent.com/8888782/92024373-2139c700-ed2c-11ea-8573-7fecacae5b9b.png)

**Comment by codingjoe** [comment]
Hi @DaEMoN33,

I presume you are talking about a frontend related issue, or rather how to make Django render the form in a way that is supported by your CSS framework. Might I ask which framework you are using and what the code your vision looks like?

Best,
Joe

**Comment by chetan1029** [comment]
Hey, @codingjoe I have the same issue with bootstrap. It shows weight and unit in the form one by one but what is best in bootstrap to use input-group forms. Is it any way we can make it with a weight text field and unit selection select field group into the input-group of bootstrap?

**Comment by codingjoe** [comment]
Hi, I honestly don't know. I haven't been using bootstrap in a while. Maybe you better look finding an answer on stackoverflow. Sorry, that I can't be of more help. Best, Joe
