### ISSUE TITLE
Cannot serialize: Mass(kg=80) when making migrations

### ISSUE THREAD

**Issue by kb1900** [coddingtonbear/django-measurement#104]
Model:
`
from measurement.measures import Weight

goal_weight = MeasurementField(measurement=Weight, null=True, blank=True, default=Weight(kg=80))
`

python manage.py makemigrations:
`
ValueError: Cannot serialize: Mass(kg=80.0)
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/3.1/topics/migrations/#migration-serializing
`

using django-measurement version 3.2.3, measurement version 3.2.0,  django version 3.1.3

**Comment by kb1900** [comment]
https://github.com/coddingtonbear/django-measurement/issues/88 may be relevant here

thanks in advance for any help!

**Comment by codingjoe** [comment]
Hi @kb1900, yes, it's the same issue as #88. I still haven't found the time to fix it myself. You are welcome to contribute a patch yourself. Best, Joe
