### ISSUE TITLE
does not work with custom measure classes (self defined)

### ISSUE THREAD

**Issue by syphar** [coddingtonbear/django-measurement#11]
```
  File ".../django_measurement/models.py", line 35, in __init__
    measurement = getattr(measures, measurement_class)
AttributeError: 'module' object has no attribute 'Loudness'
```

**Comment by codingjoe** [comment]
@syphar do you have any clue to why this happens?

**Comment by syphar** [comment]
seems like we expect the measure class (by class name) to be in the measurements.measures module

**Comment by codingjoe** [comment]
You should be able to define measurement with the class instead of using the literal in the meaturement_class kwarg.

**Comment by jochszch** [comment]
@codingjoe 
I am having the same issue. I have defined my own Measurement class, and that is used in creating the model field. 

model.py:
> flow_amount = MeasurementField(measurement=FlowRate)

makemigrations:
> File "/usr/local/lib/python2.7/dist-packages/django_measurement/models.py", line 36, in __init__
>     measurement = getattr(measures, force_text(measurement_class))
> AttributeError: 'module' object has no attribute 'FlowRate'. 

How am I suppose to do to use my own measurement? or is there a work around?

**Comment by coddingtonbear** [comment]
I think what @codingjoe is saying, @jochszch, is that you can specify your measurement class with

```python
flow_amount = MeasurementField(measurement_class=FlowRate)
```

Could you give that a shot?

**Comment by jochszch** [comment]
@coddingtonbear 

With measurement_class, i get this when making migration
```
File "/usr/local/lib/python2.7/dist-packages/django_measurement/models.py", line 36, in __init__
    measurement = getattr(measures, force_text(measurement_class))
AttributeError: 'module' object has no attribute '<class 'custom_measurement.FlowRate'>'
```

**Comment by jochszch** [comment]
I have another measurement class written for Area because django.gis.measurement doesn't come with hectares and acres. And weirdly that one works, I used the measurement kwarg not measurement_class.

```
from custom_measurement import Area
...
area = MeasurementField(measurement=Area)
```

**Comment by gstos** [comment]
I have the same issue with a Density class. I am not an expert in Django internals though. I hope this insight helps. I added two prints in the __init__ of the MeasurementField to output the __repr__ of what the field is receiving as measurement and measurement_class. 

When I call makemigrations, the model initializes perfectly during Django init cycle, and the output is:
- measurement: <class 'commons.measures.density.Density'>
- measurement_class: None

When Django starts to dig into the migration details, this happens:
- measurement: None
- measurement_class: 'Density'
AttributeError: module 'measurement.measures' has no attribute 'Density'

It looks like something happens during the serialization process.

**Comment by coddingtonbear** [comment]
Awesome; thanks for the details, @gstos; I'm going to try to find a little time to look at this this weekend.

**Comment by gstos** [comment]
I hope I can save some precious weekend time! I see two ways to explore - one was to make the measurement class serializable (maybe using @deconstructible decorator from django.utils.deconstruct, but that would make things more complicated for users, break things and honestly I don't know if it will work... probably you've gone this path before. 

The second way, which I have made it work through the migration process, but haven't tested further was as follows:

- Store the full "path" of the class (i.e. module_name.measurement_class)
- Rebuild it with the help of importlib from any location
- Still need to consider the case where the class.__module__ is None or empty (as per my research, that seems to happen sometimes) - I haven't dig any further
- I haven't gone through all the possibilities here, so there may be a much more obvious solution in the same route. Also, I am not an expert in Django internals - so, that may break things from previous versions, migrations, etc. - so please use it carefully.

Please feel free to add any thoughts. 

`
class MeasurementField(FloatField):
    # ... some code skipped...

    def __init__(self, verbose_name=None, name=None, measurement=None,
                 measurement_class=None, unit_choices=None, *args, **kwargs):

        if not measurement and measurement_class:
            if type(measurement_class) != str:
                # Previous case - we probably should use the same logic that I used below
                # - i.e. module.measurement__class
                measurement = getattr(measures, force_text(measurement_class))
            else:
                # Some logic to recover the class with its full name with importlib (not ideal!)
                *module_name, cls = measurement_class.split('.')
                module_name = '.'.join(module_name)
                if module_name:
                    module = importlib.import_module(module_name)
                    measurement = getattr(module, cls, None)
                else:
                    # raise some error?
                    pass

        if not measurement:
            raise TypeError('MeasurementField() takes a measurement'
                            ' keyword argument. None given.')

        if not issubclass(measurement, self.MEASURE_BASES):
            raise TypeError(
                'MeasurementField() takes a measurement keyword argument.'
                ' It has to be a valid MeasureBase subclass.'
            )

        self.measurement = measurement
        # Storing the full name of the class, which is the only parameter that gets serialized
        self.measurement_class = force_text(measurement.__module__ + '.' + measurement.__name__)
        self.widget_args = {
            'measurement': measurement,
            'unit_choices': unit_choices,
        }

        super(MeasurementField, self).__init__(verbose_name, name,
                                               *args, **kwargs)
`

**Comment by mcneillj** [comment]
Ran into the same issue here in v3.0.0.  I have a lot of units that I need to add (e.g. pressure, irradiance, enthalpy,  etc.).  It would be nice if MeasurementField accepted any appropriately formatted class rather than referencing back to the measurement.measures module.  Instead of 

`measurement = getattr(measures, measurement_class)`

could the argument be the actually class rather than looking up the class from measurement.measures?  That would eliminate the issue with paths between default and custom measurements being different.

**Comment by codingjoe** [comment]
@mcneillj I agree this seems the more plausible way to do it. I would even introduce a new backwards incompatible change. I would really welcome this change in a PR 😉

**Comment by webit-mdowney** [comment]
I have submitted a pull request for review.

**Comment by codingjoe** [comment]
@webit-mdowney thanks! I left a commend.

For documentation purposes: I would prefer to import measure in migrations. They won't work if the class moved anyways, so this is the less obscure approach in my opinion.

**Comment by pvandriessche** [comment]
Hey, Do you know when this will be available in the master?

**Comment by codingjoe** [comment]
@pvandriessche once you create a pull-request  for it ;)
Not seriously that would really help. I didn't find the time yet to implement this myself. I maintain too many packages :/

**Comment by webit-mdowney** [comment]
@pvandriessche build upon my PR 😄 

We are already using it in production anyway 👍
