### ISSUE TITLE
Bug in Mass and Distance classes

### ISSUE THREAD

**Issue by patryktomaszewski** [coddingtonbear/django-measurement#110]
Hey, it happens only with particular units and values. I get very strange rounding:
![image](https://user-images.githubusercontent.com/58734528/150369296-e4e132a3-fa02-489b-90e4-d90ae6c51e9f.png)

For now I noticed problem with inch, lb and it happens only with value = 3

**Comment by coddingtonbear** [comment]
Are you surprised that we're showing a long decimal?   If so: don't be surprised -- that's just a side-effect of using floating point numbers.  You'll see the same effect everywhere where floating point values are used (and it's the very reason why we tell folks to not use floating point fields when dealing with currency).

You can read more about it here: https://django-measurement.readthedocs.io/en/latest/topics/storing.html#how-is-this-data-stored
and https://floating-point-gui.de/
