### ISSUE TITLE
Docs issue(?): django_measurement.measures doesn't exist

### ISSUE THREAD

**Issue by alexjj** [coddingtonbear/django-measurement#23]
In the docs it says to use:
```
from django_measurement.models import MeasurementField
from django_measurement.measures import Weight,Volume
```

but django_measurement only contains models, utils and forms. The weight/volume etc. come from measurement.measures. 

so shouldn't this be:
```
from django_measurement.models import MeasurementField
from measurement.measures import Weight,Volume
```

Or am I doing something wrong?

**Comment by coddingtonbear** [comment]
Oh! No, you're doing it exactly right -- it looks like the docs haven't been updated since the measurement classes were moved into the `measurement` library.  Sorry about that!
