### ISSUE TITLE
TypeError: MeasurementField() takes a measurement keyword argument. None given.

### ISSUE THREAD

**Issue by sachitad** [coddingtonbear/django-measurement#24]
I have a model attribute like so:
weight = MeasurementField(Weight)

I am not able to run server or migrations.
Here is the full traceback:
https://gist.github.com/sachitad/bcd164be24182c352a16

I am on django==1.9.2

**Comment by codingjoe** [comment]
Hi @sachitad why don't you try this:
```python weight = MeasurementField(measurement=Weight)```

**Comment by sachitad** [comment]
Thanks @codingjoe. It worked. Docs should be updated though to cover this.
