### ISSUE TITLE
Calculation based on external model value

### ISSUE THREAD

**Issue by synnack** [coddingtonbear/django-measurement#68]
Hi, 

Is it possible to have the measurement conversion look at a different field for the conversion?

What I'm looking for a way to convert different types of fuel between metric, imperial, but also between volume and weight. :)

Essentially, things like gallons per hour, litres per hour, grams per second, grams per hour.

For 1 type of fuel this is simple, just create a custom Fuel measure class and define the conversions there, then create a bi-dimensional measurement that has Fuel over time.

Now, the problem is that I have 2 main types of fuel: one at 0.721 kg/l, and one at 0.804 kg/l.

For multiple types of fuel, it needs to find the conversion somewhere else in the model class..

From the point of view of the field, it'll be in the parent (model) and there in a field with the value stored there.

**Comment by codingjoe** [comment]
Hi @synnack I don't think using a value from another field is a wise idea. I would recommend to just add a new metric and a new field. The metric you seem to be looking for is [volumetric flow rate](https://en.wikipedia.org/wiki/Volumetric_flow_rate).

**Comment by OmenApps** [comment]
@codingjoe now that we have volumetric flow in python-measurement, this issue can probably be closed out.

**Comment by synnack** [comment]
Damn, I forgot about this issue :)

Volumetric flow rate is exactly what I do not want, it's flow rate.. but the input may be volumetric or mass.

**Comment by synnack** [comment]
Essentially, I want to use mass as a base for all calculations, but it may store volume+fuel.. for instance, 20 US Gallon per hour of JetA, Jet B, 100LL Avgas or Diesel. Those have different masses, so the conversion is dependent on the fuel, but you want to input the values that you have, which may be in GPH, LPH or (better) g/s

**Comment by codingjoe** [comment]
I think in this case I would recommend doing the calculation in your form or view on a model mutation method. Not inside the field. Besides, this use case is too uncommon to implement it in the package itself. If you want to implement such behavior inside the field, you'd need to subclass it. Best. Joe
