### ISSUE TITLE
Any i18n options?

### ISSUE THREAD

**Issue by diogosimao** [coddingtonbear/django-measurement#78]
Would like to ask if are there any options for locale? Or how would the package behave with it in Django?

**Comment by codingjoe** [comment]
That depends, SI units are the same in all languages. The only units that could be problematic are imperial units as well as time units. You check check out the units [here](https://github.com/coddingtonbear/python-measurement/tree/master/measurement/measures). Those are used to create the choices.

**Comment by codingjoe** [comment]
In any case I will close the issue, since it would need to be done in `python-measurement` anyway.
https://github.com/coddingtonbear/python-measurement
