### ISSUE TITLE
Default value set to 0 returns an int instead of measurement instance

### ISSUE THREAD

**Issue by Pacu2** [coddingtonbear/django-measurement#81]
Given that I have a field:
```
from django_measurement.models import MeasurementField
from measurement.measures import Mass


class Product(models.Model):
    weight = MeasurementField(measurement=Mass, default=0)
```

I'd expect the default value to be set to `Mass(any_unit=0)` instead of `0` as an int.

```
In [5]: Product.objects.create().weight
Out[5]: 0
```

**Comment by codingjoe** [comment]
@Pacu2 I am not sure if I follow. You set `0` as the default value but don't expect it to be `0`. How about you do set the default to `Mass(any_unit=0)`? This works, or does it not?

**Comment by codingjoe** [comment]
Hi yes, this is correct, this does work, but line 2 will throw a warning telling not to do so ;)
https://github.com/coddingtonbear/django-measurement/blob/725f47fa524ec493a38b454a552f576e7e04f6e8/django_measurement/models.py#L98-L106
